projectDjango/btest/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

projectDjango/projectDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('btest/', include('btest.urls')),
]

projectDjango/btest/models.py
from django.db import models

class Bb(models.Model):
  title = models.CharField(max_length=50, verbose_name='Товар')
  content = models.TextField(null=True, blank=True, verbose_name='Описание')
  price = models.FloatField(null=True, blank=True, verbose_name='Цена')
  published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
  
  class Meta:
    verbose_name_plural = 'Объявления'
    verbose_name = 'Объявление'
    ordering = ['-published']

class Rubric(models.Model):
  name = models.CharField(max_length=20, db_index=True,  verbose_name='Название')
  def __str__(self):
    return self.name
  class Meta:
    verbose_name_plural = 'Рубрики'
    verbose_name = 'Рубрика'
    ordering = ['name']


class Collection(models.Model):
  name = models.CharField(max_length=50, verbose_name='Название')
  content = models.TextField(null=True, blank=True, verbose_name='Краткое описание')
  start_date= models.DateTimeField(null=True,verbose_name='Период показа')
  fin_date= models.DateTimeField(null=True,verbose_name='Период показа')
  zal= models.ForeignKey('Zal', null=True,   on_delete=models.PROTECT, verbose_name='Выставочный зал')
  
  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name_plural = 'Коллекции'
    verbose_name = 'Коллекция'
    ordering = ['name']

class Exponat(models.Model):
  name = models.CharField(max_length=50, verbose_name='Название')
  content = models.TextField(null=True, blank=True, verbose_name='Краткое описание')
  stoimost = models.FloatField(null=True, blank=True, verbose_name='Страховая стоимость')
  vek_sozdania = models.FloatField(null=True, blank=True, verbose_name='Век создания')
  visota = models.FloatField(null=True, blank=True, verbose_name='Высота')
  shirina = models.FloatField(null=True, blank=True, verbose_name='Ширина')
  dlina = models.FloatField(null=True, blank=True, verbose_name='Длина')
  collection = models.ForeignKey('Collection', null=True,   on_delete=models.PROTECT, verbose_name='Коллекция')
  price = models.FloatField(null=True, blank=True, verbose_name='Цена')
  
  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name_plural = 'Экспонаты'
    verbose_name = 'Экспонат'
    ordering = ['name']

class Zal(models.Model):
  name = models.CharField(max_length=50, verbose_name='Название')
  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name_plural = 'Выставочные залы'
    verbose_name = 'Выставочный зал'
    ordering = ['name']

projectDjango/btest/views.py
from .models import *
from django.shortcuts import render
 
def index(request):
    bbs = Collection.objects.all()
    rbs = Exponat.objects.all()
    tbs = Zal.objects.all()
    
    return render(request, "btest/index.html", {'bbs': bbs, 'rbs1': rbs, 'tbs': tbs })

projectDjango/btest/templates/btest/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
	<title>Главная - Доска объявлений</title>
</head>
<body>
	<!--<h1>Объявления</h1>
	{% for bb in bbs %}
	<div>
		<h2>{{ bb.title }}</h2>
		<p>{{ bb.content }}</p>
		<p>{{ bb.published|date:"d.m.Y. H:i:s"}}</p>
		<p>{{ bb.rubric.name}}</p>
	</div>
	{% endfor %}
	-->
	<h1>Коллекции</h1>
	{% for collection in bbs %}
	<div>
		<p> Название коллекции - {{ collection.name }}</p>
		<p> Описание коллекции - {{ collection.content }}</p>
		<p> Дата начала коллекции - {{ collection.start_date}}</p>
		<p> Дата окончания коллекции -{{ collection.fin_date}}</p>
		<p> Зал, в котором размещена коллекция: {{ collection.zal}}</p>
	</div>
	{% endfor %}
	
	<h1>Экспонаты</h1>
	{% for exponat in rbs1 %}
	<div>
		<h3> Название экспоната - {{ exponat.name }}</h3>
		<p> Краткое описание: {{ exponat.content }}</p>
		<p> Стоимость: {{ exponat.stoimost}}</p>
		<p> Век создания: {{ exponat.vek_sozdania}}</p>
		<p>Высота экспоната:{{ exponat.visota}}</p>
		<p>Ширина экспоната: {{ exponat.shirina}}</p>
		<p>Длина экспоната: {{ exponat.dlina}}</p>
		<p>Коллекция, к котороый относится: {{ exponat.collection}}</p>
		<p>Цена: {{ exponat.price}}</p>
	</div>
	{% endfor %}
	
	<h1>Выставочные залы</h1>
	{% for zal in tbs %}
	<div>
		<h2> Зал {{ zal.name }}</h2>
		{% for collection in zal.collection_set.all %}
		<div>
		<h2>Название коллекции: {{ collection.name }}</h2>
		<p>Даты начала - окончания: {{ collection.start_date}} - {{ collection.fin_date}}</p>
		</div>
		{% endfor %}
		
		{% for exponat in collection.exponat_set.all %}
		<div>
		<h2>{{ exponat.name }}</h2>
		<p>{{ exponat.content }}</p>
		<p>{{ exponat.stoimost}}</p>
		<p>{{ exponat.vek_sozdania}}</p>
		<p>{{ exponat.visota}}</p>
		<p>{{ exponat.shirina}}</p>
		<p>{{ exponat.dlina}}</p>
		<p>{{ exponat.collection}}</p>
		<p>{{ exponat.price}}</p>
		</div>
		{% endfor %}
		
	</div>
	{% endfor %}
	
</body>
</html>